name: brew pr-pull

on:
  pull_request_target:
    types: [labeled]

permissions: {}
jobs:
  pr-pull:
    if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      checks: read
      contents: write
      issues: read
      packages: write
      pull-requests: write
    steps:
      - uses: Homebrew/actions/setup-homebrew@7f6df1cd36597249cbf9810ff3aeff47edf8243b
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: Homebrew/actions/git-user-config@c62170a03ff2bcb9ab097fd7d6acbc905618e42a

      - run: brew pr-pull --debug --tap="$GITHUB_REPOSITORY" "$PULL_REQUEST"
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.repository_owner }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}

      - uses: Homebrew/actions/git-try-push@a72774738da65503fcf62f33ec305aa1452acf7d

      - run: git push --delete origin "$BRANCH"
        if: github.event.pull_request.head.repo.fork == false
        env:
          BRANCH: ${{ github.event.pull_request.head.ref }}
