name: Test
on:
  push:
  pull_request:
  schedule: [{ cron: "0 0 10 * *" }] # monthly https://crontab.guru/#0_0_10_*_*
  workflow_dispatch:

permissions: {}
jobs:
  test:
    uses: nodenv/.github/.github/workflows/test.yml@bd27009d5f178c0a88d42f7b07e6a3c7623ed768 # v7.0.8
    with: { npm: false }
    permissions:
      contents: read
      packages: read
      id-token: write
      security-events: write
      statuses: write

  brew-audit:
    runs-on: macos-latest
    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with: { egress-policy: audit }
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { persist-credentials: false }

      - run: brew tap nodenv/nodenv .
      - name: brew audit
        run: |
          for formula in Formula/*; do
            brew audit --strict "nodenv/nodenv/$(basename "${formula%.rb}")"
          done

  brew-install:
    runs-on: macos-latest
    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with: { egress-policy: audit }
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { persist-credentials: false }

      - run: brew tap nodenv/nodenv .
      - name: brew install
        run: |
          for formula in Formula/*; do
            brew install "nodenv/nodenv/$(basename "${formula%.rb}")"
          done
      - name: brew test
        run: |
          for formula in Formula/*; do
            brew test "nodenv/nodenv/$(basename "${formula%.rb}")"
          done
